version: "3.8"

services:
  first-sample:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    image: grpc-first-sample-img
    container_name: grpc-first-sample-cont
    ports:
      - 9999:9999
    command: sh
    tty: true
    volumes:
      - .:/first-sample
