version: "3.8"
  
services:  
  first-sample:  
    build:
      context: ./build/docker
      dockerfile: Dockerfile
    image: grpc-first-sample-img
    container_name: grpc-first-sample-cont
    ports:
      - 9999:9999
    command: sh
    tty: true
    volumes:
      - .:/first-sample